name: Ask a Question
description: Ask a question about a blog post, or anything else tech-related
title: "[Question]: "
labels: [ "question" ]
assignees:
  - mmillican
body:
  - type: markdown
    attributes:
      value: |
        Describe your question and link to the relevant blog post.
